name: Cypress Tests

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  cypress-linux:
    name: Cypress Tests on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallel-run: [1, 2, 3]  # Parallel instances within Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a stable LTS version

      - name: Install dependencies
        run: npm install

      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV
        shell: bash

      - name: Run Cypress tests in parallel (Ubuntu)
        run: |
          npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} \
            --ci-build-id "${{ github.run_id }}-linux"

  cypress-macos:
    name: Cypress Tests on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        parallel-run: [1, 2, 3]  # Parallel instances within MacOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV
        shell: bash

      - name: Run Cypress tests in parallel (MacOS)
        run: |
          npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} \
            --ci-build-id "${{ github.run_id }}-macos"

  cypress-windows:
    name: Cypress Tests on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        parallel-run: [1, 2, 3]  # Parallel instances within Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV
        shell: bash

      - name: Run Cypress tests in parallel (Windows)
        run: |
          npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} \
            --ci-build-id "${{ github.run_id }}-windows"
