name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-linux:
    name: Cypress Tests on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallel-run: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create OS-Specific Reports Directory
        run: mkdir -p cypress/reports/linux/.jsons

      - name: Run Cypress tests (Ubuntu)
        run: |
          npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} \
            --ci-build-id "${{ github.run_id }}-linux"

  cypress-macos:
    name: Cypress Tests on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        parallel-run: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create OS-Specific Reports Directory
        run: mkdir -p cypress/reports/darwin/.jsons

      - name: Run Cypress tests (MacOS)
        run: |
          npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} \
            --ci-build-id "${{ github.run_id }}-macos"

  cypress-windows:
    name: Cypress Tests on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        parallel-run: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create OS-Specific Reports Directory (Windows)
        run: New-Item -Path cypress/reports/win32/.jsons -ItemType Directory -Force
        shell: pwsh

      - name: Run Cypress tests (Windows)
        run: |
          npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} `
            --ci-build-id "${{ github.run_id }}-windows"
        shell: pwsh
